Do not alter semantics when propagating class constants
Class constants can trigger NoClassDefFoundErrors, so we must be careful to not propagate them into other sections where the trap handler is different.