rolling back to revision 2728: "fix" by Patrick introduces multiple new bugs, including...
java.lang.RuntimeException: trying to hash null value.
       at soot.util.HashChain.getPredOf(HashChain.java:338)
       at soot.PatchingChain.getPredOf(PatchingChain.java:225)
       at
soot.toolkits.graph.ExceptionalUnitGraph.buildExceptionDests(ExceptionalUnitGraph.java:337)
       at
soot.toolkits.graph.ExceptionalUnitGraph.initialize(ExceptionalUnitGraph.java:263)
       at
soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:149)
       at
soot.toolkits.graph.ExceptionalUnitGraph.<init>(ExceptionalUnitGraph.java:182)
       at
soot.toolkits.scalar.LocalSplitter.internalTransform(LocalSplitter.java:77)
       at soot.BodyTransformer.transform(BodyTransformer.java:51)
       at soot.Transform.apply(Transform.java:104)
       at soot.JimpleBodyPack.applyPhaseOptions(JimpleBodyPack.java:57)
       at soot.JimpleBodyPack.internalApply(JimpleBodyPack.java:89)
       at soot.Pack.apply(Pack.java:124)
       at soot.coffi.CoffiMethodSource.getBody(CoffiMethodSource.java:117)
       at soot.SootMethod.getBodyFromMethodSource(SootMethod.java:82)
       at soot.SootMethod.retrieveActiveBody(SootMethod.java:329)
       at
soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:181)
       at
soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:81)
       at soot.jimple.spark.solver.OnFlyCallGraph.build(OnFlyCallGraph.java:55)
       at soot.jimple.spark.solver.PropWorklist.handleVarNode(PropWorklist.java:123)
       at soot.jimple.spark.solver.PropWorklist.propagate(PropWorklist.java:53)
       at
soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:151)
       at soot.SceneTransformer.transform(SceneTransformer.java:39)
       at soot.Transform.apply(Transform.java:89)
       at soot.RadioScenePack.internalApply(RadioScenePack.java:57)
       at
soot.jimple.toolkits.callgraph.CallGraphPack.internalApply(CallGraphPack.java:47)
       at soot.Pack.apply(Pack.java:114)
       at soot.PackManager.runWholeProgramPacks(PackManager.java:406)
       at soot.PackManager.runPacks(PackManager.java:327)
       at soot.Main.run(Main.java:202)
       at soot.Main.main(Main.java:145)
       
(see thread "How to obtain the topological graph in the transactional transformation phase (wjtp.tn)?")